binmap unit testing (#34)
* binmap unit testing

Commented out tests are due to missing a function. There are two tests
failing which may be bugs.

=== RUN   TestInitGet
--- PASS: TestInitGet (0.00s)
=== RUN   TestNavigation
--- PASS: TestNavigation (0.00s)
=== RUN   TestOverflows
--- PASS: TestOverflows (0.00s)
=== RUN   TestAdvanced
--- PASS: TestAdvanced (0.00s)
=== RUN   TestBinToString
--- PASS: TestBinToString (0.00s)
=== RUN   TestSetGet
--- PASS: TestSetGet (0.00s)
=== RUN   TestChess
--- PASS: TestChess (0.00s)
=== RUN   TestStaircase
--- PASS: TestStaircase (0.00s)
=== RUN   TestHole
--- PASS: TestHole (0.00s)
=== RUN   TestFind
    TestFind: map_test.go:87:
        	Error Trace:	map_test.go:87
        	Error:      	Not equal:
        	            	expected: 0x4
        	            	actual  : 0x0
        	Test:       	TestFind
--- FAIL: TestFind (0.00s)
=== RUN   TestCover
--- PASS: TestCover (0.00s)
=== RUN   TestSeqLength
    TestSeqLength: map_test.go:143:
        	Error Trace:	map_test.go:143
        	Error:      	Not equal:
        	            	expected: 11
        	            	actual  : 0
        	Test:       	TestSeqLength
--- FAIL: TestSeqLength (0.00s)
=== RUN   TestEmptyFilled
--- PASS: TestEmptyFilled (0.00s)
=== RUN   TestFindFilled1
--- PASS: TestFindFilled1 (0.00s)
=== RUN   TestFindFilled2
--- PASS: TestFindFilled2 (0.00s)
=== RUN   TestFindFilled3
--- PASS: TestFindFilled3 (0.00s)
FAIL
coverage: 55.1% of statements
exit status 1
FAIL	github.com/MemeLabs/go-ppspp/pkg/binmap	0.004s

* fix binmap.Map.FindEmpty bug

Co-authored-by: Slugalisk <slugalisk@gmail.com>