more tests for mdstore profile store and storage key
=== RUN   TestVerifyCertificateRequest
=== RUN   TestVerifyCertificateRequest/success
=== RUN   TestVerifyCertificateRequest/invalid_key_length
=== RUN   TestVerifyCertificateRequest/invalid_key_type_(x25519)
--- PASS: TestVerifyCertificateRequest (0.00s)
    --- PASS: TestVerifyCertificateRequest/success (0.00s)
    --- PASS: TestVerifyCertificateRequest/invalid_key_length (0.00s)
    --- PASS: TestVerifyCertificateRequest/invalid_key_type_(x25519) (0.00s)
=== RUN   TestSignCertificateRequest
=== RUN   TestSignCertificateRequest/success
=== RUN   TestSignCertificateRequest/invalid_key_length
=== RUN   TestSignCertificateRequest/invalid_key_type_(x25519)
--- PASS: TestSignCertificateRequest (0.00s)
    --- PASS: TestSignCertificateRequest/success (0.00s)
    --- PASS: TestSignCertificateRequest/invalid_key_length (0.00s)
    --- PASS: TestSignCertificateRequest/invalid_key_type_(x25519) (0.00s)
=== RUN   TestCreateProfile
--- PASS: TestCreateProfile (0.09s)
=== RUN   TestCreateProfileUsernameTaken
--- PASS: TestCreateProfileUsernameTaken (0.13s)
=== RUN   TestDeleteProfile
--- PASS: TestDeleteProfile (0.07s)
=== RUN   TestGetProfiles
    TestGetProfiles: require.go:72:
        	Error Trace:	require.go:72
        	            				metadata_store_test.go:71
        	Error:      	Not equal:
        	            	expected: 3
        	            	actual  : 0
        	Test:       	TestGetProfiles
--- FAIL: TestGetProfiles (0.20s)
=== RUN   TestInit
--- PASS: TestInit (0.07s)
=== RUN   TestDeleteProfileStore
--- PASS: TestDeleteProfileStore (0.06s)
=== RUN   TestGetProfile
    TestGetProfile: require.go:442:
        	Error Trace:	require.go:442
        	            				profile_store_test.go:54
        	Error:      	Expected value not to be nil.
        	Test:       	TestGetProfile
--- FAIL: TestGetProfile (0.07s)
=== RUN   TestNewStorageKey
--- PASS: TestNewStorageKey (0.07s)
=== RUN   TestMarshalAndUnmarshalStorageKey
--- PASS: TestMarshalAndUnmarshalStorageKey (0.13s)
=== RUN   TestSealAndOpen
--- PASS: TestSealAndOpen (0.07s)
FAIL
exit status 1
FAIL	github.com/MemeLabs/go-ppspp/pkg/dao	0.947s