lint: deadcode and errcheck
pkg/wgutil/wgutil.go:100:6: `publicKeyFromPrivate` is unused (deadcode)
func publicKeyFromPrivate(priv []byte) crypto.PublicKey {
     ^
pkg/node/heficed.go:458:6: `heficedTenants` is unused (deadcode)
type heficedTenants struct {
     ^
internal/backend/backend.go:770:6: `copyFile` is unused (deadcode)
func copyFile(src, dst string) error {
     ^
internal/cmd/root.go:41:6: `er` is unused (deadcode)
func er(msg interface{}) {
     ^
cmd/cli/main.go:8:13: Error return value of `cmd.Execute` is not checked (errcheck)
	cmd.Execute()
	           ^
pkg/node/dreamhost.go:131:16: ineffectual assignment to `err` (ineffassign)
	keypairsList, err := keypairs.ExtractKeyPairs(keypairsPager)
	              ^